baseurl = "https://preview.exa.education/"
languageCode = "en-us"
title = "Hugo Creative Theme"
theme = "master"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Hugo Creative Theme"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"

	#HOME PAGE

	# Head section
	[params.index.head]
		image = "/images/headfront.png"

	[params.business.head]
		image = "/images/headfront.png"

	# Hero section
	[params.index.hero]
		slogan     = "Business Page"
		subtitle   = "This is the new page for business"
		buttonText = "Find out more"


	# About section
	[params.index.about]
		headline    = ""
		description = "<p>The Internet has never been as important to your business as it is today.</p>  <p>Your Internet Service Provider should be one of your most valuable business partners.</p>"
		image = "/images/Digital_Handshake.png"
		buttonText  = "Get started!"


	# Service section
	[params.index.services]
		headline = "Custom Business Internet Services from Exa Networks"

		[[params.index.services.text]]
			info = "Specialising in high quality services and bespoke solutions, Exa Networks provides the business sector with custom-built Internet provision throughout the UK."
			info1 = "Small, medium or large, we'll work with you to deliver the best possible Internet services for your company, whether you're looking for ultrafast Internet connectivity, a managed Wide Area Network, VoIP, or practically any other kind of service."
			info2 = "Our network is hosted by some of the largest, and best run data centres in Europe, including TeleCity, TeleHouse, AQL as well as our own custom built data centres."
			info3 = "We're dedicated to bringing you the best service and support you'll find. From the start, we give every business customer their own account manager to ensure smooth service from inception to implementation, backing that up with award-winning customer care."
			info4 = "If you ever need to call us, you won't have to deal with long hold and wait times - our expert team are on hand throughout extended business hours, and are ready to fix any problems you have."

    	[[params.index.services.solution]]
    		title = "Find the Perfect Internet Solution Today"
    		number = "0345 145 1234"
    		email = "Solutions@exa.net.uk"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"

	#BUSINESS PAGE
